[package]
name = "aleph-language"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dashu-float = "0.4.3"
dashu-int = "0.4.1"
nom = "7.1.3"
